// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://hycjhmrbfurdzwsfzaeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5Y2pobXJiZnVyZHp3c2Z6YWVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUzNzQ4OTQsImV4cCI6MjA4MDk1MDg5NH0.K5GIeclNj0ZuY423dIMhQsJ9Y54e1_k7YvQnLzN1yUs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Safe storage implementation that handles localStorage errors gracefully
const safeStorage = {
  getItem: (key: string) => {
    try {
      return localStorage?.getItem(key) ?? null;
    } catch (error) {
      console.warn('localStorage access denied:', error);
      return null;
    }
  },
  setItem: (key: string, value: string) => {
    try {
      localStorage?.setItem(key, value);
    } catch (error) {
      console.warn('localStorage write failed:', error);
    }
  },
  removeItem: (key: string) => {
    try {
      localStorage?.removeItem(key);
    } catch (error) {
      console.warn('localStorage remove failed:', error);
    }
  },
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeStorage as any,
    persistSession: true,
    autoRefreshToken: true,
  }
});
